table Auditorias
	lineageTag: 7be14eea-7259-4537-90fd-7847def48aa5

	column Fecha
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: bdee0dcd-3e67-4675-8e67-1de86ec07703
		summarizeBy: none
		sourceColumn: Fecha

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column legajo
		dataType: double
		lineageTag: 1a3c73a7-b467-4444-ae70-f5df82401792
		summarizeBy: sum
		sourceColumn: legajo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sector
		dataType: string
		lineageTag: 3cc5b7ad-6c6c-4ab0-af0b-b893429a0a05
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Super
		dataType: string
		lineageTag: 098bd7dc-f61d-42df-bc28-2a2ad36d8c0c
		summarizeBy: none
		sourceColumn: Super

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: b4e96e6c-8049-4d72-9e4c-8edf9dff5306
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Agente
		dataType: string
		lineageTag: ae45b7bd-3ad3-4944-a0c0-e45bef937089
		summarizeBy: none
		sourceColumn: Agente

		annotation SummarizationSetBy = Automatic

	column ID_Llamada
		dataType: string
		lineageTag: a8e3763b-bc38-46d1-adb3-baaf86930575
		summarizeBy: none
		sourceColumn: ID_Llamada

		annotation SummarizationSetBy = Automatic

	column CorreoAuditor
		dataType: string
		lineageTag: 4e98c62c-cb7d-4500-8d12-857b7651afc2
		summarizeBy: none
		sourceColumn: CorreoAuditor

		annotation SummarizationSetBy = Automatic

	column Nombre_Auditor
		dataType: string
		lineageTag: c381719a-f1c0-4813-9cfb-bea3a28d5e82
		summarizeBy: none
		sourceColumn: Nombre_Auditor

		annotation SummarizationSetBy = Automatic

	column Cargo_Auditor
		dataType: string
		lineageTag: 9a80dcbb-7763-4568-9bfa-a9e3df6cc979
		summarizeBy: none
		sourceColumn: Cargo_Auditor

		annotation SummarizationSetBy = Automatic

	column Respuesta
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 8b9f8818-9aad-41b8-a28f-cd6935537a1f
		summarizeBy: sum
		sourceColumn: Respuesta

		annotation SummarizationSetBy = Automatic

	column Base
		dataType: string
		lineageTag: b3c05766-483d-4521-a42d-a8ca5b9bf9a4
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

	partition Auditorias = m
		mode: import
		source =
				let
				    Origen = Sql.Database("10.148.226.40\REPORTING", "REPORTING", [Query="WITH NominaAntiguedad AS#(lf)(#(lf)    SELECT#(lf)        CAST(NA.fecha AS DATE) AS Fecha,#(lf)        NA.leg,#(lf)        NA.sec_descrip,#(lf)        NA.Super,#(lf)        NA.Team,#(lf)        NA.Agente,#(lf)        ROW_NUMBER() OVER#(lf)        (#(lf)            PARTITION BY #(lf)                CAST(NA.fecha AS DATE),#(lf)                NA.leg#(lf)            ORDER BY #(lf)                NA.leg#(lf)        ) AS RN#(lf)    FROM Planificacion.Nomina.NominaAntiguedad NA#(lf)),#(lf)#(lf)Nomina AS#(lf)(#(lf)    SELECT #(lf)        PU.fecha,#(lf)        PU.legajo,#(lf)        PU.usuario,#(lf)        NA.sec_descrip,#(lf)        NA.Super,#(lf)        NA.Team,#(lf)        NA.Agente#(lf)    FROM [Planificacion].[Nomina].[Nomina_User_Avaya] PU#(lf)#(lf)    LEFT JOIN NominaAntiguedad NA#(lf)        ON PU.legajo = NA.leg#(lf)        AND CAST(PU.fecha AS DATE) = NA.Fecha#(lf)        AND NA.RN = 1#(lf)#(lf)    WHERE PU.fecha IS NOT NULL#(lf)),#(lf)#(lf)Auditores AS#(lf)(#(lf)    SELECT#(lf)        NA.leg,#(lf)        NA.Agente AS Nombre_Auditor,#(lf)        NA.car_descrip,#(lf)        PD.Correo,#(lf)#(lf)        ROW_NUMBER() OVER#(lf)        (#(lf)            PARTITION BY #(lf)                NA.leg,#(lf)                LOWER(LTRIM(RTRIM(PD.Correo)))#(lf)            ORDER BY #(lf)                NA.leg#(lf)        ) AS RN#(lf)#(lf)    FROM Planificacion.Nomina.NominaAntiguedad NA#(lf)#(lf)    LEFT JOIN [Planificacion].[Nomina].[PD_Usuarios] PD#(lf)        ON NA.leg = PD.legajo#(lf)#(lf)    WHERE PD.Correo IS NOT NULL#(lf)),#(lf)#(lf)Auditorias AS#(lf)(#(lf)    SELECT   #(lf)        CAST([Fecha Auditoria] AS DATE) AS Fecha, #(lf)        CAST([Identificador Conversacion] AS VARCHAR(100)) AS ID_Llamada, #(lf)        CAST(Agente AS VARCHAR(200)) AS Agente, #(lf)        Auditor, #(lf)        Instancia, #(lf)        Campana,#(lf)#(lf)        CASE#(lf)            WHEN TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', '')) > 1#(lf)                THEN TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', '')) / 100#(lf)            ELSE TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', ''))#(lf)        END AS Respuesta,#(lf)#(lf)        'WHATSAPP' AS Marca #(lf)    FROM Reporting.WO.AuditoriasWhatsapp #(lf)#(lf)    UNION ALL#(lf)#(tab)#(lf)    SELECT   #(lf)        CAST([Fecha Auditoria] AS DATE) AS Fecha, #(lf)        CAST([Verint Contact ID] AS VARCHAR(100)) AS ID_Llamada, #(lf)        CAST(Agente AS VARCHAR(200)) AS Agente, #(lf)        Auditor, #(lf)        Instancia, #(lf)        Campana,#(lf)#(lf)        CASE#(lf)            WHEN TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', '')) > 1#(lf)                THEN TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', '')) / 100#(lf)            ELSE TRY_CONVERT(NUMERIC(10,4), REPLACE(CAST(Respuesta AS VARCHAR(50)), '%', ''))#(lf)        END AS Respuesta,#(lf)#(lf)        'JAZZTEL' AS Marca #(lf)    FROM Reporting.WO.AuditoriasJazztel #(lf) #(lf)    UNION ALL #(lf) #(lf)    SELECT   #(lf)        CAST([Fecha Auditoria] AS DATE) AS Fecha, #(lf)        CAST([Verint Contact ID] AS VARCHAR(100)) AS ID_Llamada, #(lf)        CAST(Agente AS VARCHAR(200)) AS Agente, #(lf)        Auditor, #(lf)        Instancia, #(lf)        Campana,#(lf)#(lf)        CAST(#(lf)            (#(lf)                (CASE WHEN [Saludo Estilo] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.10) +#(lf)                (CASE WHEN [Soy Claro Fiable] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.15) +#(lf)                (CASE WHEN [Soluciono] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.25) +#(lf)                (CASE WHEN [Resumo] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.20) +#(lf)                (CASE WHEN [Pregunta Solucion] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.20) +#(lf)                (CASE WHEN [Despedida Estilo] IN ('SI', 'N/A') THEN 1.0 ELSE 0.0 END * 0.10)#(lf)            ) AS NUMERIC(10,4)#(lf)        ) AS Respuesta,#(lf)#(lf)        'ORANGE' AS Marca #(lf)#(lf)    FROM Reporting.WO.AuditoriasOrange#(lf)),#(lf)#(lf)WEB AS#(lf)(#(lf)    SELECT#(lf)        A.Fecha,#(lf)        N.legajo,#(lf)        N.sec_descrip AS Sector,#(lf)        N.Super,#(lf)        N.Team,#(lf)        N.Agente,#(lf)#(lf)        A.ID_Llamada,#(lf)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)WHEN LOWER(LTRIM(RTRIM(A.Auditor))) LIKE '%@masorange.es'#(lf)#(tab)#(tab)#(tab)#(tab)THEN LEFT(#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)LOWER(LTRIM(RTRIM(A.Auditor))),#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)CHARINDEX('@', LOWER(LTRIM(RTRIM(A.Auditor)))) - 1#(lf)#(tab)#(tab)#(tab)#(tab)) + '@orange.es'#(lf)#(tab)#(tab)#(tab)ELSE LOWER(LTRIM(RTRIM(A.Auditor)))#(lf)#(tab)#(tab)END AS CorreoAuditor,#(lf)        AU.Nombre_Auditor,#(lf)        AU.car_descrip AS Cargo_Auditor,#(lf)#(lf)        A.Respuesta,#(lf)        'WEB' AS Base#(lf)#(lf)    FROM Nomina N#(lf)#(lf)    INNER JOIN Auditorias A#(lf)        ON CAST(N.Fecha AS DATE) = CAST(A.Fecha AS DATE)#(lf)        AND N.usuario = A.Agente#(lf)#(lf)    LEFT JOIN Auditores AU#(lf)    ON#(lf)    CASE#(lf)        WHEN LOWER(LTRIM(RTRIM(A.Auditor))) LIKE '%@masorange.es'#(lf)            THEN LEFT(#(lf)                LOWER(LTRIM(RTRIM(A.Auditor))),#(lf)                CHARINDEX('@', LOWER(LTRIM(RTRIM(A.Auditor)))) - 1#(lf)            ) + '@orange.es'#(lf)        ELSE LOWER(LTRIM(RTRIM(A.Auditor)))#(lf)    END#(lf)    =#(lf)    CASE#(lf)        WHEN LOWER(LTRIM(RTRIM(AU.Correo))) LIKE '%@masorange.es'#(lf)            THEN LEFT(#(lf)                LOWER(LTRIM(RTRIM(AU.Correo))),#(lf)                CHARINDEX('@', LOWER(LTRIM(RTRIM(AU.Correo)))) - 1#(lf)            ) + '@orange.es'#(lf)        ELSE LOWER(LTRIM(RTRIM(AU.Correo)))#(lf)    END#(lf)    AND AU.RN = 1#(lf)),#(lf)#(lf)ICEBERG AS#(lf)(#(lf)    SELECT#(lf)        CAST(IC.[Fecha Auditoria] AS DATE) AS Fecha,#(lf)        IC.[Legajo] AS legajo,#(lf)#(lf)        N.sec_descrip AS Sector,#(lf)        N.Super,#(lf)        N.Team,#(lf)        N.Agente,#(lf)#(lf)        CAST(NULL AS VARCHAR(100)) AS ID_Llamada,#(lf)#(lf)        CAST(IC.[Legajo Auditor] AS VARCHAR(200)) AS CorreoAuditor,#(lf)        CAST(IC.[Auditor] AS VARCHAR(200)) AS Nombre_Auditor,#(lf)        CAST(IC.[Cargo Auditor] AS VARCHAR(200)) AS Cargo_Auditor,#(lf)#(lf)        CAST(#(lf)            TRY_CONVERT(NUMERIC(10,4), IC.[Nota Calidad]) / 100#(lf)            AS NUMERIC(10,4)#(lf)        ) AS Respuesta,#(lf)#(lf)        'ICEBERG' AS Base#(lf)#(lf)    FROM [ModulosIceberg].[Calidad].[PlantillaCalidadUnificada] IC#(lf)#(lf)    LEFT JOIN Nomina N#(lf)        ON CAST(IC.[Fecha Auditoria] AS DATE) = CAST(N.Fecha AS DATE)#(lf)        AND IC.[Legajo] = N.legajo#(lf)#(lf)    WHERE IC.[Fecha Auditoria] >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) - 2, 0)#(lf)      AND IC.[Fecha Auditoria] < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0)#(lf))#(lf)#(lf)SELECT#(lf)    Fecha,#(lf)    legajo,#(lf)    Sector,#(lf)    Super,#(lf)    Team,#(lf)    Agente,#(lf)    ID_Llamada,#(lf)    CorreoAuditor,#(lf)    Nombre_Auditor,#(lf)    Cargo_Auditor,#(lf)    Respuesta,#(lf)    Base#(lf)#(lf)FROM WEB#(lf)#(lf)UNION ALL#(lf)#(lf)SELECT#(lf)    Fecha,#(lf)    legajo,#(lf)    Sector,#(lf)    Super,#(lf)    Team,#(lf)    Agente,#(lf)    ID_Llamada,#(lf)    CorreoAuditor,#(lf)    Nombre_Auditor,#(lf)    Cargo_Auditor,#(lf)    Respuesta,#(lf)    Base#(lf)#(lf)FROM ICEBERG#(lf)where Agente is not null#(lf)ORDER BY Fecha DESC;"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Respuesta", Percentage.Type}, {"Fecha", type date}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

